version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-biofeedback
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biofeedback
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: biofeedback-api
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/api.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=biofeedback;Username=postgres;Password=postgres
    volumes:
      - ./certs:/https:ro
    expose:
      - "443"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: biofeedback-frontend
    expose:
      - "80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
