version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-biofeedback
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biofeedback
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ./server/server
      dockerfile: Dockerfile
    container_name: biofeedback-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=biofeedback;Username=postgres;Password=postgres
    expose:
      - "80"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./web/biofeedback-web
      dockerfile: Dockerfile
    container_name: biofeedback-frontend
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data: